openapi: 3.0.0
info:
  title: IQRAPATH Student API
  description: API for the IQRAPATH Student Mobile Application
  version: 1.0.0
  contact:
    name: IQRAPATH Support
    url: https://iqrapath.com/support
    email: support@iqrapath.com

servers:
  - url: https://api.iqrapath.com/api/v1
    description: Production API Server
  - url: https://staging.iqrapath.com/api/v1
    description: Staging API Server
  - url: http://localhost:8000/api/v1
    description: Local Development Server

security:
  - bearerAuth: []

paths:
  /student/stats:
    get:
      summary: Get Student Statistics
      description: Retrieves statistics about a student's classes, including total, completed, and upcoming classes.
      tags:
        - Student Dashboard
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A successful response with student statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      stats:
                        type: object
                        properties:
                          totalClasses:
                            type: integer
                            example: 7
                          completedClasses:
                            type: integer
                            example: 5
                          upcomingClasses:
                            type: integer
                            example: 2
        '401':
          description: Unauthorized - Authentication required
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Failed to retrieve student stats"
                      details:
                        type: string
                        example: "Error message details"

  /student/upcoming-classes:
    get:
      summary: Get Student Upcoming Classes
      description: Retrieves a list of upcoming classes for the authenticated student.
      tags:
        - Student Dashboard
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A successful response with upcoming classes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      upcomingClasses:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: "123"
                            title:
                              type: string
                              example: "Tajweed - Intermediate"
                            teacher:
                              type: string
                              example: "Ustadh Ahmed Abdullah"
                            date:
                              type: string
                              example: "Monday, March 18, 2025"
                            timeRange:
                              type: string
                              example: "4:00 PM - 5:00 PM"
                            status:
                              type: string
                              enum: [confirmed, pending, cancelled]
                              example: "confirmed"
                            image:
                              type: string
                              example: "/assets/images/classes/tajweed.png"
        '401':
          description: Unauthorized - Authentication required
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Failed to retrieve upcoming classes"
                      details:
                        type: string
                        example: "Error message details"

  /students/{id}:
    get:
      summary: Get Student Details
      description: Retrieves detailed information about a specific student.
      tags:
        - Student Management
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The student ID
      responses:
        '200':
          description: Student details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      phone_number:
                        type: string
                      location:
                        type: string
                      status:
                        type: string
                      registration_date:
                        type: string
                        format: date
                  preferences:
                    type: object
                    nullable: true
                  subscription:
                    type: object
                    nullable: true

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from the authentication endpoint 